### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by fleuriafluoride** [Pomax/tex2utf#10]
This repository does not have a licence. While the package for `tex2mail` within CTAN also does not state any licence, `tex2mail` in a slightly modified form is bundled with [PARI/GP](https://pari.math.u-bordeaux.fr), licensed under GPL 2.0-or-later, where the author of the script is a major contributor. I believe this implies the version of `tex2mail` bundled with PARI/GP should be covered under the GPL, and so this repository should also be covered under the GPL.

If I am correct, I'd appreciate you adding proper licensing notices, as I want to use `tex2utf` in my own work, but the current lack of clear licensing makes me hesitant to do so.

**Comment by Pomax** [comment]
`tex2mail` itself, as distributed through CTAN, does not state any license, so I'm not going to copy one from a completely different project that the original author happens to be involved with =)
